[package]
name = "tetris-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.3"
embedded-hal = "1.0.0"
microbit-v2 = "0.15.1"
panic-halt = "0.2.0"
panic-rtt-target = "0.1.3"
rtt-target = "0.5.0"

[profile.release]
panic = 'abort'

[profile.dev]
panic = 'abort'
