[package]
name = "tetris-lib"
version = "0.1.0"
edition = "2021"

[features]
default = []
std-log = ["log"]
defmt-log = ["defmt"]

[dependencies]
smart-leds = "0.4.0"
no_std_strings = "0.1.3"
log = { version = "0.4", optional = true }
defmt = { version = "1", optional = true }
