[build]
# Default to Android ARM64 target
target = "aarch64-linux-android"

[target.aarch64-linux-android]
linker = "aarch64-linux-android21-clang"

[target.x86_64-linux-android]
linker = "x86_64-linux-android21-clang"
